#!/bin/bash

#Change values for username on lines 10,11 and change values for Your Name and Your Email on lines 19,20
repoName=$1

mkdir $repoName 
cd $repoName

git init
curl -u 'username' https://api.github.com/user/repos -d '{"name":"'$1'"}'
git remote add origin https://github.com/username/"$1".git

touch README.md
touch .gitignore

echo "# $1" > README.md
echo ".DS_Store" > .gitignore

git config --global user.name "Your Name"
git config --global user.email "Your email"

git add .
git commit -m "Initial commit"
git push -u origin master
